version: '3'

services:
  master:
    build: master/
    command: python ./master.py
    ports:
      - 5000:5000
      - 5001:5001
      - 5002:5002
      - 5003:5003
      - 5004:5004
      - 5005:5005
      - 5006:5006
    container_name: actividad2_master
  slave1:
    build: slave1/
    command: python ./slave1.py
    network_mode: host
    depends_on:
      - master
    container_name: actividad2_slave1
  slave2:
    build: slave2/
    command: python ./slave2.py
    network_mode: host
    depends_on:
      - master
      - slave1
    container_name: actividad2_slave2
  slave3:
    build: slave3/
    command: python ./slave3.py
    network_mode: host
    depends_on:
      - master
      - slave1
      - slave2
    container_name: actividad2_slave3
  client:
    build: client/
    command: python ./cliente.py
    network_mode: host
    depends_on:
      - master
      - slave1
      - slave2
      - slave3
    container_name: actividad2_client
    stdin_open: True
    tty: True